spring:
  application:
    name: book

logging:
  level:
    root: trace # 所有目录设置日志级别
    com: # 分目录设置日志级别
      wjl:
        controller: error
  file:
    name: logger/test.log
  logback:
    rollingpolicy:
      max-file-size: 1kb

server:
  port: 9090
my:
  key1: 1
  key2: true

# 类
person:
  name: "wjl"
  age: 19

list:
  - item1
  - item2
  - item3

captcha:
  width: 400
  height: 200
  time-limit: 60
  unit: 1000