spring:
    application:
        name: mcp-demo
    ai:
        dashscope:
            api-key: sk-a5f277ca38f8426ba23c68a313c6c46b
        mcp:
            client:
                stdio:
                    servers-configuration: classpath:/mcp/mcp-server-config.json
